### ISSUE TITLE
Upstream tracker

### ISSUE THREAD

**Issue by pi0** [unjs/cookie-es#7]
Tracking upstream changes in [jshttp/cookie](https://github.com/jshttp/cookie) to be backported.

History: https://github.com/jshttp/cookie/blob/master/HISTORY.md

Types upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cookie/index.d.ts

Last check: v0.6.0 (on 29 march 2024)

0.6.0
- [x] https://github.com/jshttp/cookie/commit/84a156749b673dbfbf43679829b15be09fbd8988

0.5.0:

- [x] https://github.com/jshttp/cookie/commit/624b4e26e8bd9f0ecbdebe68ba585fc9744ddb10
- [x] https://github.com/jshttp/cookie/commit/7c65abe3515165b1e06ab3f6c5064e00b06b6e99
- [x] https://github.com/jshttp/cookie/commit/042073f1d679b9c7fb7d64660d3c6d372bd1f468
- [x] https://github.com/jshttp/cookie/commit/16ded6894d38d653b5c7c6ad34f6ea0a1e6c0938

0.4.2:

- [x] https://github.com/jshttp/cookie/commit/009b3cb1f818c6dccd7ef70a805602ba06297a0e
- [x] https://github.com/jshttp/cookie/commit/aa1a335d2b85e919c028c59d1d13db3fc371502b

**Comment by NozomuIkuta** [comment]
How about setting up a workflow that periodically checks the upstream repository and create an issue (or a comment) if it has made changes and/or release since the last execution?

Unfortunately, as far as I researched, there is no way a repository "subscribes" (push) to other repositories' changes.
So we have to set up a workflow that "checks" (pull) the changes by itself. 

If you like it, I could work on it.

Refs:

- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by pi0** [comment]
That would be a nice idea using (weekly maybe?) schedules. We can keep a file like `.upstream` with last commit hash in upstream rebased and action to update/create issue if a new one available? (either way feel free to work on it would be cool project!)

**Comment by NozomuIkuta** [comment]
📝 There is an issue about ESM support in upstream
https://github.com/jshttp/cookie/issues/152

**Comment by pi0** [comment]
@NozomuIkuta do you still want to work on automation? based the fact the uptes on upstream are not so often, it probably is not that critical for this repo but a generic "fork tracker" applet might be nice idea. It could be a github app for example.
